version: "3.8"
services:
  api:
    image: minakshi2463/fastapi-app:latest
    env_file:
      - .env
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"


  postgres:
    image: postgres:16
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgres
    restart: always
    expose:
      - "5432"

  redis:
    image: redis:7
    networks:
      - backend
    restart: always
    expose: 
      - "6379"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml    


networks:
  backend:
    driver: bridge

volumes:
  postgres_data:  
